
#!/bin/sh
# Terraform Import Script generated by gcloud cli


terraform import module.entire-tf-output.google_bigquery_table.pull_requests projects/solar-attic-352013/datasets/source__github/tables/pull_requests
terraform import module.entire-tf-output.google_service_account.dataform_executor projects/solar-attic-352013/serviceAccounts/dataform-executor@solar-attic-352013.iam.gserviceaccount.com
terraform import module.entire-tf-output.google_service_account.github_importer projects/solar-attic-352013/serviceAccounts/github-importer@solar-attic-352013.iam.gserviceaccount.com
terraform import module.entire-tf-output.google_service_account.teraform projects/solar-attic-352013/serviceAccounts/teraform@solar-attic-352013.iam.gserviceaccount.com
terraform import module.entire-tf-output.google_bigquery_dataset.source__github projects/solar-attic-352013/datasets/source__github
